### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by 0xJepsen** [SorellaLabs/ethers-reth#4]
Hey just wanted to get in touch about this project, we want to use it in [arbiter](https://github.com/primitivefinance/arbiter) and are interesting in contributing and comparing this approach to our current approach. We ended up building a decent amount of custom logic for it in the `simulate` crate which was kinda a pain. Are you guys open to outside contributions? Do you need help with project management (issues, contribution guidelines, etc)?

**Comment by Autoparallel** [comment]
Also here to see where this is at!

**Comment by 0xvanbeethoven** [comment]
Hi,

Absolutely, we welcome outside contributions and any help with project management would be greatly appreciated. As I mentioned on tg, the main goal of this project was to speed up backtesting. Let's collaborate to further enhance this functionality.

Best,
Ludwig
